version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
    entrypoint: /code/entrypoint.sh
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
